package providers

// ProviderModels maps provider aliases/IDs to their supported models in 9router.
// Ported verbatim from open-sse/providers/registry (registry/{id}.js models arrays,
// keyed by uiAlias/alias and by provider id so both lookups resolve).
var ProviderModels = map[string][]string{
	"aai":                  {"universal-3-pro", "universal-2", "best", "nano"},
	"af":                   {"gpt-oss-120b", "gpt-oss-20b", "kimi-k2.7-code"},
	"ag":                   {"gemini-3.8-flash-high", "gemini-3.8-flash-medium", "gemini-3.8-flash-low", "gemini-3.8-flash", "gemini-3.7-flash-high", "gemini-3.7-flash-medium", "gemini-3.7-flash-low", "gemini-3.6-flash-high", "gemini-3.6-flash-medium", "gemini-3.6-flash-low", "gemini-3.5-flash-high", "gemini-3-flash-agent", "gemini-3.5-flash-low", "gemini-3.5-flash-extra-low", "gemini-pro-agent", "gemini-3.1-pro-low", "claude-sonnet-4-6", "claude-opus-4-6-thinking", "gpt-oss-120b-medium", "gemini-3-flash", "gemini-3.1-flash-image"},
	"aionlabs":             {"aion-labs/aion-3.5", "aion-labs/aion-3.5-mini", "aion-labs/aion-3.0", "aion-labs/aion-3.0-mini", "aion-labs/aion-2.0", "aion-labs/aion-rp-llama-3.1-8b"},
	"alicode":              {"qwen3.5-plus", "kimi-k2.5", "glm-5", "MiniMax-M2.5", "qwen3-max-2026-01-23", "qwen3-coder-next", "qwen3-coder-plus", "glm-4.7"},
	"alicode-intl":         {"qwen3.5-plus", "kimi-k2.5", "glm-5", "MiniMax-M2.5", "qwen3-coder-next", "qwen3-coder-plus", "glm-4.7"},
	"alims-intl":           {"qwen3.5-plus", "kimi-k2.5", "glm-5", "MiniMax-M2.5", "qwen3-coder-next", "qwen3-coder-plus", "glm-4.7"},
	"alitp-intl":           {"qwen3.8-max-preview", "qwen3.7-max", "qwen3.7-plus", "qwen3.6-flash", "glm-5.2", "deepseek-v4-pro"},
	"anthropic":            {"claude-sonnet-4-20250514", "claude-opus-4-20250514", "claude-3-5-sonnet-20241022"},
	"antigravity":          {"gemini-3.8-flash-high", "gemini-3.8-flash-medium", "gemini-3.8-flash-low", "gemini-3.8-flash", "gemini-3.7-flash-high", "gemini-3.7-flash-medium", "gemini-3.7-flash-low", "gemini-3.6-flash-high", "gemini-3.6-flash-medium", "gemini-3.6-flash-low", "gemini-3.5-flash-high", "gemini-3-flash-agent", "gemini-3.5-flash-low", "gemini-3.5-flash-extra-low", "gemini-pro-agent", "gemini-3.1-pro-low", "claude-sonnet-4-6", "claude-opus-4-6-thinking", "gpt-oss-120b-medium", "gemini-3-flash", "gemini-3.1-flash-image"},
	"api-airforce":         {"gpt-oss-120b", "gpt-oss-20b", "kimi-k2.7-code"},
	"ark":                  {"Doubao-Seed-2.0-Code", "Doubao-Seed-2.0-pro", "Doubao-Seed-2.0-lite", "Doubao-Seed-Code", "DeepSeek-V4-Flash", "DeepSeek-V4-Pro", "GLM-5.1", "MiniMax-M2.7", "Kimi-K2.6"},
	"assemblyai":           {"universal-3-pro", "universal-2", "best", "nano"},
	"baidu":                {"deepseek-v4-pro", "deepseek-v4-flash", "glm-5.2", "glm-5.1", "kimi-k2.6", "qwen3.5-397b-a17b", "qwen3.5-27b"},
	"bazaarlink":           {"auto:free", "claude-opus-4.7", "claude-sonnet-4.6", "claude-haiku-4.5", "gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "grok-4.3", "grok-4.20", "gemini-3.1-pro-preview", "gemini-3-flash-preview", "gemini-3.1-flash-lite-preview", "kimi-k2.6", "kimi-k2.5", "glm-5.1", "glm-5", "mimo-v2.5-pro", "mimo-v2.5", "minimax-m3", "minimax-m2.7", "minimax-m2.5", "qwen3.6-plus", "nemotron-3-super-120b-a12b"},
	"bb":                   {"claude-fable-5", "claude-opus-4.8", "claude-sonnet-4.6", "gpt-5.5", "gpt-5.4-pro", "gpt-5.4", "gpt-5.3-codex", "gpt-5.4-nano", "deepseek-v4-flash", "grok-4.3"},
	"bfl":                  {"flux-pro-1.1", "flux-pro-1.1-ultra", "flux-pro", "flux-dev", "flux-kontext-pro", "flux-kontext-max"},
	"black-forest-labs":    {"flux-pro-1.1", "flux-pro-1.1-ultra", "flux-pro", "flux-dev", "flux-kontext-pro", "flux-kontext-max"},
	"blackbox":             {"claude-fable-5", "claude-opus-4.8", "claude-sonnet-4.6", "gpt-5.5", "gpt-5.4-pro", "gpt-5.4", "gpt-5.3-codex", "gpt-5.4-nano", "deepseek-v4-flash", "grok-4.3"},
	"bluesminds":           {"gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "claude-sonnet-4-5", "claude-haiku-4-5", "gemini-2.0-flash", "gemini-2.0-flash-exp", "qwen-turbo", "kimi-k2", "kimi-k2-thinking", "glm-4.7", "minimax-m2.5", "claude-opus-4-5", "gemini-2.5-pro"},
	"bm":                   {"gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "claude-sonnet-4-5", "claude-haiku-4-5", "gemini-2.0-flash", "gemini-2.0-flash-exp", "qwen-turbo", "kimi-k2", "kimi-k2-thinking", "glm-4.7", "minimax-m2.5", "claude-opus-4-5", "gemini-2.5-pro"},
	"bpm":                  {"seed-2-0-pro-260328", "seed-2-0-code-preview-260328", "seed-2-0-mini-260215", "seed-2-0-lite-260228", "kimi-k2-thinking-251104", "glm-4-7-251222", "gpt-oss-120b-250805"},
	"byteplus":             {"seed-2-0-pro-260328", "seed-2-0-code-preview-260328", "seed-2-0-mini-260215", "seed-2-0-lite-260228", "kimi-k2-thinking-251104", "glm-4-7-251222", "gpt-oss-120b-250805"},
	"bzl":                  {"auto:free", "claude-opus-4.7", "claude-sonnet-4.6", "claude-haiku-4.5", "gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "grok-4.3", "grok-4.20", "gemini-3.1-pro-preview", "gemini-3-flash-preview", "gemini-3.1-flash-lite-preview", "kimi-k2.6", "kimi-k2.5", "glm-5.1", "glm-5", "mimo-v2.5-pro", "mimo-v2.5", "minimax-m3", "minimax-m2.7", "minimax-m2.5", "qwen3.6-plus", "nemotron-3-super-120b-a12b"},
	"cbai":                 {"glm-5.2", "glm-5.1", "glm-5.0", "glm-5.0-turbo", "glm-5v-turbo", "glm-4.7", "minimax-m3", "minimax-m2.7", "kimi-k2.7", "kimi-k2.6", "kimi-k2.5", "hy3-preview", "deepseek-v4-pro", "deepseek-v4.1-flash", "deepseek-v3-2-volc"},
	"cbcn":                 {"glm-5.2", "glm-5.1", "glm-5v-turbo", "minimax-m3", "kimi-k2.7", "kimi-k2.6", "hy3", "hy4-preview", "glm-5.3", "glm-5.3-flash", "kimi-k3-1", "deepseek-v4-pro", "deepseek-v4.1-flash"},
	"cc":                   {"claude-opus-5", "claude-fable-5-1", "claude-fable-5", "claude-sonnet-5", "claude-haiku-4-5-20251001"},
	"cerebras":             {"gpt-oss-120b", "zai-glm-4.7", "llama-3.3-70b", "llama-4-scout-17b-16e-instruct", "qwen-3-235b-a22b-instruct-2507", "qwen-3-32b"},
	"cf":                   {"@cf/meta/llama-3.2-1b-instruct", "@cf/meta/llama-3.2-3b-instruct", "@cf/meta/llama-3.1-8b-instruct-fp8-fast", "@cf/meta/llama-3.1-8b-instruct-awq", "@cf/mistralai/mistral-small-3.1-24b-instruct", "@cf/meta/llama-3.1-70b-instruct-fp8-fast", "@cf/meta/llama-3.3-70b-instruct-fp8-fast", "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", "@cf/moonshotai/kimi-k2.5", "@cf/moonshotai/kimi-k2.6", "@cf/zai-org/glm-4.7-flash", "@cf/qwen/qwq-32b", "@cf/qwen/qwen2.5-coder-32b-instruct", "@cf/black-forest-labs/flux-2-klein-9b", "@cf/black-forest-labs/flux-2-klein-4b", "@cf/black-forest-labs/flux-2-dev", "@cf/leonardo/lucid-origin", "@cf/leonardo/phoenix-1.0", "@cf/black-forest-labs/flux-1-schnell", "@cf/bytedance/stable-diffusion-xl-lightning", "@cf/lykon/dreamshaper-8-lcm", "@cf/runwayml/stable-diffusion-v1-5-img2img", "@cf/runwayml/stable-diffusion-v1-5-inpainting", "@cf/stabilityai/stable-diffusion-xl-base-1.0"},
	"cl":                   {"anthropic/claude-opus-4.7", "anthropic/claude-sonnet-4.6", "anthropic/claude-opus-4.6", "openai/gpt-5.3-codex", "openai/gpt-5.4", "google/gemini-3.1-pro-preview", "google/gemini-3.1-flash-lite-preview", "kwaipilot/kat-coder-pro"},
	"claude":               {"claude-opus-5", "claude-fable-5-1", "claude-fable-5", "claude-sonnet-5", "claude-haiku-4-5-20251001"},
	"cline":                {"anthropic/claude-opus-4.7", "anthropic/claude-sonnet-4.6", "anthropic/claude-opus-4.6", "openai/gpt-5.3-codex", "openai/gpt-5.4", "google/gemini-3.1-pro-preview", "google/gemini-3.1-flash-lite-preview", "kwaipilot/kat-coder-pro"},
	"clinepass":            {"cline-pass/glm-5.2", "cline-pass/kimi-k2.7-code", "cline-pass/kimi-k2.6", "cline-pass/deepseek-v4-pro", "cline-pass/deepseek-v4-flash", "cline-pass/mimo-v2.5", "cline-pass/mimo-v2.5-pro", "cline-pass/minimax-m3", "cline-pass/qwen3.7-max", "cline-pass/qwen3.7-plus"},
	"cloudflare-ai":        {"@cf/meta/llama-3.2-1b-instruct", "@cf/meta/llama-3.2-3b-instruct", "@cf/meta/llama-3.1-8b-instruct-fp8-fast", "@cf/meta/llama-3.1-8b-instruct-awq", "@cf/mistralai/mistral-small-3.1-24b-instruct", "@cf/meta/llama-3.1-70b-instruct-fp8-fast", "@cf/meta/llama-3.3-70b-instruct-fp8-fast", "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", "@cf/moonshotai/kimi-k2.5", "@cf/moonshotai/kimi-k2.6", "@cf/zai-org/glm-4.7-flash", "@cf/qwen/qwq-32b", "@cf/qwen/qwen2.5-coder-32b-instruct", "@cf/black-forest-labs/flux-2-klein-9b", "@cf/black-forest-labs/flux-2-klein-4b", "@cf/black-forest-labs/flux-2-dev", "@cf/leonardo/lucid-origin", "@cf/leonardo/phoenix-1.0", "@cf/black-forest-labs/flux-1-schnell", "@cf/bytedance/stable-diffusion-xl-lightning", "@cf/lykon/dreamshaper-8-lcm", "@cf/runwayml/stable-diffusion-v1-5-img2img", "@cf/runwayml/stable-diffusion-v1-5-inpainting", "@cf/stabilityai/stable-diffusion-xl-base-1.0"},
	"cmc":                  {"deepseek/deepseek-v4-pro", "deepseek/deepseek-v4-flash", "moonshotai/Kimi-K2.7-Code", "moonshotai/Kimi-K2.7-Code-Highspeed", "moonshotai/Kimi-K2.6", "moonshotai/Kimi-K2.5", "zai-org/GLM-5.2", "zai-org/GLM-5.2-Fast", "zai-org/GLM-5.1", "zai-org/GLM-5", "MiniMaxAI/MiniMax-M3", "MiniMaxAI/MiniMax-M2.7", "MiniMaxAI/MiniMax-M2.5", "xiaomi/mimo-v2.5-pro", "xiaomi/mimo-v2.5", "Qwen/Qwen3.6-Max-Preview", "Qwen/Qwen3.6-Plus", "Qwen/Qwen3.7-Max", "Qwen/Qwen3.7-Plus", "stepfun/Step-3.7-Flash", "stepfun/Step-3.5-Flash", "nvidia/nemotron-3-ultra-550b-a55b"},
	"codebuddy-cn":         {"glm-5.2", "glm-5.1", "glm-5v-turbo", "minimax-m3", "kimi-k2.7", "kimi-k2.6", "hy3", "hy4-preview", "glm-5.3", "glm-5.3-flash", "kimi-k3-1", "deepseek-v4-pro", "deepseek-v4.1-flash"},
	"codebuddy-intl":       {"glm-5.2", "glm-5.1", "glm-5.0", "glm-5.0-turbo", "glm-5v-turbo", "glm-4.7", "minimax-m3", "minimax-m2.7", "kimi-k2.7", "kimi-k2.6", "kimi-k2.5", "hy3-preview", "deepseek-v4-pro", "deepseek-v4.1-flash", "deepseek-v3-2-volc"},
	"codex":                {"gpt-6-astra", "gpt-5.6-sol", "gpt-5.6-sol-review", "gpt-5.6-terra", "gpt-5.6-terra-review", "gpt-5.6-luna", "gpt-5.6-luna-review", "gpt-5.5", "gpt-5.5-review", "gpt-5.4", "gpt-5.4-review", "gpt-5.4-mini", "gpt-5.4-mini-review", "gpt-5.3-codex-spark", "gpt-5.3-codex-spark-review", "codex-auto-review", "gpt-image-2.5", "gpt-image-2.5-flare", "gpt-image-2.5-sunburst", "gpt-image-2", "gpt-image-1.5", "gpt-5.6-sol-image", "gpt-5.6-terra-image", "gpt-5.6-luna-image", "gpt-5.5-image", "gpt-5.4-image", "gpt-5.3-image"},
	"cohere":               {"command-r-plus-08-2024", "command-r-08-2024", "command-a-03-2025"},
	"comfyui":              {"flux-dev", "sdxl"},
	"commandcode":          {"deepseek/deepseek-v4-pro", "deepseek/deepseek-v4-flash", "moonshotai/Kimi-K2.7-Code", "moonshotai/Kimi-K2.7-Code-Highspeed", "moonshotai/Kimi-K2.6", "moonshotai/Kimi-K2.5", "zai-org/GLM-5.2", "zai-org/GLM-5.2-Fast", "zai-org/GLM-5.1", "zai-org/GLM-5", "MiniMaxAI/MiniMax-M3", "MiniMaxAI/MiniMax-M2.7", "MiniMaxAI/MiniMax-M2.5", "xiaomi/mimo-v2.5-pro", "xiaomi/mimo-v2.5", "Qwen/Qwen3.6-Max-Preview", "Qwen/Qwen3.6-Plus", "Qwen/Qwen3.7-Max", "Qwen/Qwen3.7-Plus", "stepfun/Step-3.7-Flash", "stepfun/Step-3.5-Flash", "nvidia/nemotron-3-ultra-550b-a55b"},
	"cu":                   {"default", "claude-4.5-opus-high-thinking", "claude-4.5-opus-high", "claude-4.5-sonnet-thinking", "claude-4.5-sonnet", "claude-4.5-haiku", "claude-4.5-opus", "gpt-5.2-codex", "claude-4.6-opus-max", "claude-4.6-sonnet-medium-thinking", "kimi-k2.5", "gemini-3-flash-preview", "gpt-5.2", "gpt-5.3-codex"},
	"cursor":               {"default", "claude-4.5-opus-high-thinking", "claude-4.5-opus-high", "claude-4.5-sonnet-thinking", "claude-4.5-sonnet", "claude-4.5-haiku", "claude-4.5-opus", "gpt-5.2-codex", "claude-4.6-opus-max", "claude-4.6-sonnet-medium-thinking", "kimi-k2.5", "gemini-3-flash-preview", "gpt-5.2", "gpt-5.3-codex"},
	"cx":                   {"gpt-6-astra", "gpt-5.6-sol", "gpt-5.6-sol-review", "gpt-5.6-terra", "gpt-5.6-terra-review", "gpt-5.6-luna", "gpt-5.6-luna-review", "gpt-5.5", "gpt-5.5-review", "gpt-5.4", "gpt-5.4-review", "gpt-5.4-mini", "gpt-5.4-mini-review", "gpt-5.3-codex-spark", "gpt-5.3-codex-spark-review", "codex-auto-review", "gpt-image-2.5", "gpt-image-2.5-flare", "gpt-image-2.5-sunburst", "gpt-image-2", "gpt-image-1.5", "gpt-5.6-sol-image", "gpt-5.6-terra-image", "gpt-5.6-luna-image", "gpt-5.5-image", "gpt-5.4-image", "gpt-5.3-image"},
	"deepgram":             {"nova-3", "nova-2", "whisper-large", "nova"},
	"deepseek":             {"deepseek-v4-pro", "deepseek-v4-pro-max", "deepseek-v4-pro-none", "deepseek-v4.1-flash", "deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "deepseek-chat", "deepseek-reasoner"},
	"dg":                   {"nova-3", "nova-2", "whisper-large", "nova"},
	"ds":                   {"deepseek-v4-pro", "deepseek-v4-pro-max", "deepseek-v4-pro-none", "deepseek-v4.1-flash", "deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "deepseek-chat", "deepseek-reasoner"},
	"fal":                  {"fal-ai/flux/schnell", "fal-ai/flux/dev", "fal-ai/flux-pro/v1.1", "fal-ai/flux-pro/v1.1-ultra", "fal-ai/recraft-v3", "fal-ai/ideogram/v2", "fal-ai/stable-diffusion-v35-large"},
	"fal-ai":               {"fal-ai/flux/schnell", "fal-ai/flux/dev", "fal-ai/flux-pro/v1.1", "fal-ai/flux-pro/v1.1-ultra", "fal-ai/recraft-v3", "fal-ai/ideogram/v2", "fal-ai/stable-diffusion-v35-large"},
	"featherless":          {"deepseek-ai/DeepSeek-V4-Pro", "deepseek-ai/DeepSeek-V4-Flash", "zai-org/GLM-5.2", "zai-org/GLM-5.1", "moonshotai/Kimi-K2.7-Code", "moonshotai/Kimi-K2.6", "moonshotai/Kimi-K2.5"},
	"fireworks":            {"accounts/fireworks/models/deepseek-v3p1", "accounts/fireworks/models/llama-v3p3-70b-instruct", "accounts/fireworks/models/qwen3-235b-a22b", "nomic-ai/nomic-embed-text-v1.5"},
	"fl":                   {"deepseek-ai/DeepSeek-V4-Pro", "deepseek-ai/DeepSeek-V4-Flash", "zai-org/GLM-5.2", "zai-org/GLM-5.1", "moonshotai/Kimi-K2.7-Code", "moonshotai/Kimi-K2.6", "moonshotai/Kimi-K2.5"},
	"gc":                   {"gemini-3.1-pro-preview", "gemini-3-pro-preview", "gemini-3-flash-preview", "gemini-3.1-flash-lite-preview", "gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite"},
	"gcli":                 {"grok-build", "grok-4.5", "grok-4.5-high", "grok-4.5-medium", "grok-4.5-low"},
	"gemini":               {"gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.6-flash", "gemini-3.5-flash-lite", "gemini-3.1-pro-preview", "gemini-3.1-flash-lite-preview", "gemini-3-flash-preview", "gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite", "gemma-4-31b-it", "gemini-embedding-2-preview", "gemini-embedding-001", "text-embedding-005", "text-embedding-004", "gemini-3.1-flash-image-preview", "gemini-3-pro-image-preview", "gemini-2.5-flash-image", "gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite", "gemini-2.0-flash", "gemini-3.1-flash-tts-preview", "gemini-2.5-flash-preview-tts", "gemini-2.5-pro-preview-tts", "embedding-001"},
	"gemini-cli":           {"gemini-3.1-pro-preview", "gemini-3-pro-preview", "gemini-3-flash-preview", "gemini-3.1-flash-lite-preview", "gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite"},
	"gh":                   {"gpt-5.2", "gpt-5.2-codex", "gpt-5.3-codex", "gpt-5.4", "gpt-5.4-mini", "claude-haiku-4.5", "claude-opus-4.5", "claude-sonnet-4.5", "claude-sonnet-4.6", "claude-opus-4.6", "claude-opus-4.7", "gemini-2.5-pro", "gemini-3-flash-preview", "gemini-3.1-pro-preview", "grok-code-fast-1", "oswe-vscode-prime", "goldeneye-free-auto", "text-embedding-3-small", "text-embedding-3-large"},
	"github":               {"gpt-5.2", "gpt-5.2-codex", "gpt-5.3-codex", "gpt-5.4", "gpt-5.4-mini", "claude-haiku-4.5", "claude-opus-4.5", "claude-sonnet-4.5", "claude-sonnet-4.6", "claude-opus-4.6", "claude-opus-4.7", "gemini-2.5-pro", "gemini-3-flash-preview", "gemini-3.1-pro-preview", "grok-code-fast-1", "oswe-vscode-prime", "goldeneye-free-auto", "text-embedding-3-small", "text-embedding-3-large"},
	"glm":                  {"glm-5.3", "glm-5.3-flash", "glm-5.2", "glm-5.1", "glm-5-turbo", "glm-5", "glm-4.7", "glm-4.6v"},
	"glm-cn":               {"glm-5.3", "glm-5.3-flash", "glm-5.2", "glm-5.1", "glm-5-turbo", "glm-5", "glm-4.7", "glm-4.6v", "glm-4.6", "glm-4.5-air"},
	"grok-cli":             {"grok-build", "grok-4.5", "grok-4.5-high", "grok-4.5-medium", "grok-4.5-low"},
	"grok-web":             {"grok-3", "grok-3-mini", "grok-3-thinking", "grok-4", "grok-4-mini", "grok-4-thinking", "grok-4-heavy", "grok-4.1-mini", "grok-4.1-fast", "grok-4.1-expert", "grok-4.1-thinking", "grok-4.2"},
	"groq":                 {"llama-3.3-70b-versatile", "meta-llama/llama-4-maverick-17b-128e-instruct", "qwen/qwen3-32b", "openai/gpt-oss-120b", "whisper-large-v3", "whisper-large-v3-turbo", "distil-whisper-large-v3-en"},
	"gw":                   {"grok-3", "grok-3-mini", "grok-3-thinking", "grok-4", "grok-4-mini", "grok-4-thinking", "grok-4-heavy", "grok-4.1-mini", "grok-4.1-fast", "grok-4.1-expert", "grok-4.1-thinking", "grok-4.2"},
	"hf":                   {"black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.1-dev", "black-forest-labs/FLUX.1-Krea-dev", "black-forest-labs/FLUX.1-Kontext-dev", "black-forest-labs/FLUX.2-dev", "black-forest-labs/FLUX.2-klein-9B", "black-forest-labs/FLUX.2-klein-4B", "black-forest-labs/FLUX.2-klein-base-9B", "black-forest-labs/FLUX.2-klein-base-4B", "stabilityai/stable-diffusion-xl-base-1.0", "stabilityai/stable-diffusion-3.5-large", "stabilityai/stable-diffusion-3.5-large-turbo", "Qwen/Qwen-Image", "Qwen/Qwen-Image-2512", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509", "Qwen/Qwen-Image-Edit-2511", "ideogram-ai/ideogram-4-fp8", "tencent/HunyuanImage-3.0", "Tongyi-MAI/Z-Image-Turbo", "krea/Krea-2-Turbo", "HiDream-ai/HiDream-I1-Fast", "playgroundai/playground-v2.5-1024px-aesthetic", "openai/whisper-large-v3", "openai/whisper-large-v3-turbo"},
	"huggingface":          {"black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.1-dev", "black-forest-labs/FLUX.1-Krea-dev", "black-forest-labs/FLUX.1-Kontext-dev", "black-forest-labs/FLUX.2-dev", "black-forest-labs/FLUX.2-klein-9B", "black-forest-labs/FLUX.2-klein-4B", "black-forest-labs/FLUX.2-klein-base-9B", "black-forest-labs/FLUX.2-klein-base-4B", "stabilityai/stable-diffusion-xl-base-1.0", "stabilityai/stable-diffusion-3.5-large", "stabilityai/stable-diffusion-3.5-large-turbo", "Qwen/Qwen-Image", "Qwen/Qwen-Image-2512", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509", "Qwen/Qwen-Image-Edit-2511", "ideogram-ai/ideogram-4-fp8", "tencent/HunyuanImage-3.0", "Tongyi-MAI/Z-Image-Turbo", "krea/Krea-2-Turbo", "HiDream-ai/HiDream-I1-Fast", "playgroundai/playground-v2.5-1024px-aesthetic", "openai/whisper-large-v3", "openai/whisper-large-v3-turbo"},
	"hunyuan":              {"hunyuan-turbos-latest", "hunyuan-t1-latest"},
	"hyp":                  {"Qwen/QwQ-32B", "deepseek-ai/DeepSeek-R1", "deepseek-ai/DeepSeek-V3", "meta-llama/Llama-3.3-70B-Instruct", "meta-llama/Llama-3.2-3B-Instruct", "Qwen/Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-Coder-32B-Instruct", "NousResearch/Hermes-3-Llama-3.1-70B"},
	"hyperbolic":           {"Qwen/QwQ-32B", "deepseek-ai/DeepSeek-R1", "deepseek-ai/DeepSeek-V3", "meta-llama/Llama-3.3-70B-Instruct", "meta-llama/Llama-3.2-3B-Instruct", "Qwen/Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-Coder-32B-Instruct", "NousResearch/Hermes-3-Llama-3.1-70B"},
	"if":                   {"qwen3-coder-plus", "qwen3-max", "qwen3-vl-plus", "qwen3-max-preview", "qwen3-235b", "qwen3-235b-a22b-instruct", "qwen3-235b-a22b-thinking-2507", "qwen3-32b", "kimi-k2", "deepseek-v3.2", "deepseek-v3.1", "deepseek-v3", "deepseek-r1", "glm-4.7", "iflow-rome-30ba3b"},
	"iflow":                {"qwen3-coder-plus", "qwen3-max", "qwen3-vl-plus", "qwen3-max-preview", "qwen3-235b", "qwen3-235b-a22b-instruct", "qwen3-235b-a22b-thinking-2507", "qwen3-32b", "kimi-k2", "deepseek-v3.2", "deepseek-v3.1", "deepseek-v3", "deepseek-r1", "glm-4.7", "iflow-rome-30ba3b"},
	"iflytek":              {"lite", "generalv3", "generalv3.5", "max-32k", "pro-128k", "4.0Ultra"},
	"kc":                   {"anthropic/claude-sonnet-4-20250514", "anthropic/claude-opus-4-20250514", "google/gemini-2.5-pro", "google/gemini-2.5-flash", "openai/gpt-4.1", "openai/o3", "deepseek/deepseek-chat", "deepseek/deepseek-reasoner"},
	"kgw":                  {"kilo-auto/free", "nvidia/nemotron-3-super-120b-a12b:free", "nvidia/nemotron-3-ultra-550b-a55b:free", "kwaipilot/kat-coder-pro-v2.5:free", "kilo-auto/frontier", "kilo-auto/balanced"},
	"kilo-gateway":         {"kilo-auto/free", "nvidia/nemotron-3-super-120b-a12b:free", "nvidia/nemotron-3-ultra-550b-a55b:free", "kwaipilot/kat-coder-pro-v2.5:free", "kilo-auto/frontier", "kilo-auto/balanced"},
	"kilocode":             {"anthropic/claude-sonnet-4-20250514", "anthropic/claude-opus-4-20250514", "google/gemini-2.5-pro", "google/gemini-2.5-flash", "openai/gpt-4.1", "openai/o3", "deepseek/deepseek-chat", "deepseek/deepseek-reasoner"},
	"kimchi":               {"minimax-m3", "kimi-k2.7", "kimi-k2.6", "kimi-k2.5", "nemotron-3-ultra-fp4", "minimax-m2.7", "claude-opus-4-6", "claude-sonnet-4-6"},
	"kimi":                 {"kimi-k3", "k3", "kimi-for-coding", "kimi-for-coding-highspeed", "kimi-k2.7-code", "kimi-k2.7-code-highspeed", "kimi-k2.6", "kimi-k2.5", "kimi-k2.5-thinking", "kimi-latest"},
	"kira":                 {"kira-3.5-pro", "kira-3.5-flash", "kira-2.5-pro", "kira-2.5-flash", "kira-flash", "kira-mini-1.0", "glm-5.3", "glm-5.3-flash", "glm-5.2", "glm-4.7-flash", "ox-alpha", "deepseek-v4-pro", "deepseek-v4-flash", "deepseek-v4.1-flash", "minimax-m3", "minimax-m2.7", "kimi-k3", "kimi-k2.8-preview", "grok-4.7", "grok-4.6", "qwen3.8-max", "qwen3.8-flash", "qwen3.8-27b", "mimo-v2.6-pro", "mimo-v2.5-pro", "coding-mimo-v2.6-flash", "gemini-3.8-flash", "gemini-3.5-flash-lite", "gpt-6-sol", "gpt-5.6-terra", "hy4", "hy3", "ling-3.0-flash"},
	"kiro":                 {"claude-opus-5", "claude-opus-5-thinking", "claude-opus-5-agentic", "claude-opus-5-thinking-agentic", "claude-opus-4.8", "claude-opus-4.8-thinking", "claude-opus-4.8-agentic", "claude-opus-4.8-thinking-agentic", "claude-opus-4.7", "claude-opus-4.7-thinking", "claude-opus-4.7-agentic", "claude-opus-4.7-thinking-agentic", "claude-opus-4.5", "claude-opus-4.5-thinking", "claude-opus-4.5-agentic", "claude-opus-4.5-thinking-agentic", "claude-sonnet-5", "claude-sonnet-4.5", "claude-haiku-4.5", "deepseek-3.2", "qwen3-coder-next", "glm-5", "MiniMax-M2.5", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "claude-sonnet-5-thinking", "claude-sonnet-4.5-thinking", "claude-haiku-4.5-thinking", "gpt-5.6-sol-thinking", "gpt-5.6-terra-thinking", "gpt-5.6-luna-thinking", "claude-sonnet-5-agentic", "claude-sonnet-4.5-agentic", "claude-haiku-4.5-agentic", "gpt-5.6-sol-agentic", "gpt-5.6-terra-agentic", "gpt-5.6-luna-agentic", "claude-sonnet-5-thinking-agentic", "claude-sonnet-4.5-thinking-agentic", "claude-haiku-4.5-thinking-agentic", "gpt-5.6-sol-thinking-agentic", "gpt-5.6-terra-thinking-agentic", "gpt-5.6-luna-thinking-agentic"},
	"kr":                   {"claude-opus-5", "claude-opus-5-thinking", "claude-opus-5-agentic", "claude-opus-5-thinking-agentic", "claude-opus-4.8", "claude-opus-4.8-thinking", "claude-opus-4.8-agentic", "claude-opus-4.8-thinking-agentic", "claude-opus-4.7", "claude-opus-4.7-thinking", "claude-opus-4.7-agentic", "claude-opus-4.7-thinking-agentic", "claude-opus-4.5", "claude-opus-4.5-thinking", "claude-opus-4.5-agentic", "claude-opus-4.5-thinking-agentic", "claude-sonnet-5", "claude-sonnet-4.5", "claude-haiku-4.5", "deepseek-3.2", "qwen3-coder-next", "glm-5", "MiniMax-M2.5", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "claude-sonnet-5-thinking", "claude-sonnet-4.5-thinking", "claude-haiku-4.5-thinking", "gpt-5.6-sol-thinking", "gpt-5.6-terra-thinking", "gpt-5.6-luna-thinking", "claude-sonnet-5-agentic", "claude-sonnet-4.5-agentic", "claude-haiku-4.5-agentic", "gpt-5.6-sol-agentic", "gpt-5.6-terra-agentic", "gpt-5.6-luna-agentic", "claude-sonnet-5-thinking-agentic", "claude-sonnet-4.5-thinking-agentic", "claude-haiku-4.5-thinking-agentic", "gpt-5.6-sol-thinking-agentic", "gpt-5.6-terra-thinking-agentic", "gpt-5.6-luna-thinking-agentic"},
	"llm7":                 {"gpt-5.5", "claude-opus-5", "deepseek-v4-flash", "grok-4.5", "kimi-k3"},
	"mimo":                 {"mimo-x-pro-preview", "mimo-x-flash-preview", "mimo-v2.5-pro", "mimo-v2.5", "mimo-v2-omni", "mimo-v2-flash", "mimo-v2.5-tts"},
	"mimo-free":            {"mimo-auto"},
	"minimax":              {"MiniMax-M3", "MiniMax-M2.7", "MiniMax-M2.5", "MiniMax-M2.1", "minimax-image-01", "speech-2.8-hd", "speech-2.8-turbo", "speech-2.6-hd", "speech-2.6-turbo", "speech-02-hd", "speech-02-turbo", "speech-01-hd", "speech-01-turbo"},
	"minimax-cn":           {"MiniMax-M3", "MiniMax-M2.7", "MiniMax-M2.5", "MiniMax-M2.1", "speech-2.8-hd", "speech-2.8-turbo", "speech-2.6-hd", "speech-2.6-turbo", "speech-02-hd", "speech-02-turbo", "speech-01-hd", "speech-01-turbo"},
	"mistral":              {"mistral-large-latest", "codestral-latest", "mistral-medium-latest", "mistral-embed"},
	"mmf":                  {"mimo-auto"},
	"morph":                {"morph-v3-large", "morph-v3-fast", "morph-qwen35-397b", "morph-minimax27-230b", "morph-qwen36-27b", "morph-dsv4flash"},
	"nanobanana":           {"nanobanana-flash", "nanobanana-pro"},
	"nb":                   {"nanobanana-flash", "nanobanana-pro"},
	"nebius":               {"meta-llama/Llama-3.3-70B-Instruct", "Qwen/Qwen3-Embedding-8B"},
	"neosantara":           {"garda-core", "archipelago-core-70b", "garda-agentic-mini", "minimax-m3-free", "minimax-m2.7-free", "glm-5.3-flash-free", "mimo-v2.5-pro-free", "deepseek-v4-flash", "gemini-3.5-flash", "claude-sonnet-4-6", "gpt-5.4-mini"},
	"nvidia":               {"minimaxai/minimax-m2.7", "minimaxai/minimax-m3", "z-ai/glm-5.2", "deepseek-ai/deepseek-v4-pro", "deepseek-ai/deepseek-v4-flash", "moonshotai/kimi-k2.6", "nvidia/nemotron-3-ultra-550b-a55b", "nvidia/nv-embedqa-e5-v5", "nvidia/parakeet-ctc-1.1b-asr", "fastpitch", "tacotron2"},
	"oc":                   {"muse-spark-1.2-contributor-free", "muse-spark-1.3-contributor-free", "union-alpha", "jev-1.13-free"},
	"ocg":                  {"deepseek-flash", "glm-5.3-flash", "glm-5.3", "glm-5.2", "glm-5.1", "kimi-k2.7-code", "kimi-k2.6", "kimi-k3", "deepseek-v4-pro", "deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "longcat-2.0", "mimo-v2.5", "mimo-v2.5-pro", "minimax-m3", "minimax-m2.7", "minimax-m2.5", "qwen3.8-max", "qwen3.8-flash", "qwen3.7-max", "qwen3.7-plus", "qwen3.6-plus", "hy4-preview", "hy3", "grok-4.6", "gpt-5.6-luna", "muse-spark-1.2-contributor", "muse-spark-1.3-contributor"},
	"ocz":                  {"claude-fable-5", "claude-fable-5-1", "claude-opus-5", "claude-opus-4-8", "claude-opus-4-7", "claude-opus-4-6", "claude-opus-4-5", "claude-sonnet-5", "claude-sonnet-4-6", "claude-sonnet-4-5", "claude-sonnet-4", "claude-haiku-4-5", "gemini-3.6-flash", "gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.5-flash-lite", "gemini-3.5-flash", "gemini-3.1-pro", "gemini-3-flash", "gpt-6-astra", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.5", "gpt-5.5-pro", "gpt-5.4", "gpt-5.4-pro", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.3-codex-spark", "gpt-5.3-codex", "gpt-5.2", "gpt-5.2-codex", "gpt-5.1", "gpt-5.1-codex-max", "gpt-5.1-codex", "gpt-5.1-codex-mini", "gpt-5", "gpt-5-codex", "gpt-5-nano", "grok-build-0.1", "grok-4.6", "grok-4.5", "muse-spark-1.3", "muse-spark-1.2", "qwen3.6-plus", "qwen3.5-plus", "deepseek-v4-pro", "deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "glm-5.3-flash", "glm-5.3", "glm-5.2", "glm-5.1", "glm-5", "minimax-m3", "minimax-m2.7", "minimax-m2.5", "kimi-k3", "kimi-k2.7-code", "kimi-k2.6", "kimi-k2.5", "big-pickle", "union-alpha", "deepseek-v4-flash-free", "mimo-v2.6-flash-free", "mimo-v2.5-free", "ling-3.0-flash-fin-free", "nemotron-3-ultra-free", "nemotron-3.5-lightning-free", "muse-spark-1.3-contributor-free", "muse-spark-1.2-contributor-free", "jev-1.13", "jev-1.13-free"},
	"ollama":               {"gpt-oss:120b", "kimi-k2.5", "glm-5", "minimax-m2.5", "glm-4.7-flash", "qwen3.5", "minimax-m3", "deepseek-v4.1-flash:cloud"},
	"openai":               {"gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.2", "gpt-5.1", "gpt-5", "gpt-5-mini", "gpt-5-nano", "gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "o3", "o3-mini", "o3-pro", "o4-mini", "o1", "o1-mini", "text-embedding-3-large", "text-embedding-3-small", "text-embedding-ada-002", "tts-1", "tts-1-hd", "gpt-4o-mini-tts", "whisper-1", "gpt-4o-transcribe", "gpt-4o-mini-transcribe", "gpt-image-2.5", "gpt-image-2.5-flare", "gpt-image-2.5-sunburst", "gpt-image-1", "dall-e-3", "dall-e-2"},
	"opencode":             {"muse-spark-1.2-contributor-free", "muse-spark-1.3-contributor-free", "union-alpha", "jev-1.13-free"},
	"opencode-go":          {"deepseek-flash", "glm-5.3-flash", "glm-5.3", "glm-5.2", "glm-5.1", "kimi-k2.7-code", "kimi-k2.6", "kimi-k3", "deepseek-v4-pro", "deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "longcat-2.0", "mimo-v2.5", "mimo-v2.5-pro", "minimax-m3", "minimax-m2.7", "minimax-m2.5", "qwen3.8-max", "qwen3.8-flash", "qwen3.7-max", "qwen3.7-plus", "qwen3.6-plus", "hy4-preview", "hy3", "grok-4.6", "gpt-5.6-luna", "muse-spark-1.2-contributor", "muse-spark-1.3-contributor"},
	"opencode-zen":         {"claude-fable-5", "claude-fable-5-1", "claude-opus-5", "claude-opus-4-8", "claude-opus-4-7", "claude-opus-4-6", "claude-opus-4-5", "claude-sonnet-5", "claude-sonnet-4-6", "claude-sonnet-4-5", "claude-sonnet-4", "claude-haiku-4-5", "gemini-3.6-flash", "gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.5-flash-lite", "gemini-3.5-flash", "gemini-3.1-pro", "gemini-3-flash", "gpt-6-astra", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.5", "gpt-5.5-pro", "gpt-5.4", "gpt-5.4-pro", "gpt-5.4-mini", "gpt-5.4-nano", "gpt-5.3-codex-spark", "gpt-5.3-codex", "gpt-5.2", "gpt-5.2-codex", "gpt-5.1", "gpt-5.1-codex-max", "gpt-5.1-codex", "gpt-5.1-codex-mini", "gpt-5", "gpt-5-codex", "gpt-5-nano", "grok-build-0.1", "grok-4.6", "grok-4.5", "muse-spark-1.3", "muse-spark-1.2", "qwen3.6-plus", "qwen3.5-plus", "deepseek-v4-pro", "deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "glm-5.3-flash", "glm-5.3", "glm-5.2", "glm-5.1", "glm-5", "minimax-m3", "minimax-m2.7", "minimax-m2.5", "kimi-k3", "kimi-k2.7-code", "kimi-k2.6", "kimi-k2.5", "big-pickle", "union-alpha", "deepseek-v4-flash-free", "mimo-v2.6-flash-free", "mimo-v2.5-free", "ling-3.0-flash-fin-free", "nemotron-3-ultra-free", "nemotron-3.5-lightning-free", "muse-spark-1.3-contributor-free", "muse-spark-1.2-contributor-free", "jev-1.13", "jev-1.13-free"},
	"openrouter":           {"openai/text-embedding-3-large", "openai/text-embedding-3-small", "openai/text-embedding-ada-002", "qwen/qwen3-embedding-8b", "perplexity/pplx-embed-v1-4b", "perplexity/pplx-embed-v1-0.6b", "nvidia/llama-nemotron-embed-vl-1b-v2:free", "openai/gpt-4o-mini-tts", "openai/tts-1-hd", "openai/tts-1", "openai/dall-e-3", "openai/gpt-image-1", "google/imagen-3.0-generate-002", "black-forest-labs/FLUX.1-schnell", "google/veo-3.1", "openai/sora-2-pro", "bytedance/seedance-2.0", "typesafe/jev-1.13"},
	"pa":                   {"perplexity/sonar", "openai/gpt-5.5", "openai/gpt-5.4", "openai/gpt-5.4-mini", "anthropic/claude-sonnet-4-6", "anthropic/claude-opus-4-8", "google/gemini-3.1-pro-preview", "xai/grok-4.20-reasoning", "perplexity/glm-5.2", "perplexity/kimi-k2.7-code", "nvidia/nemotron-3-super-120b-a12b"},
	"perplexity":           {"sonar-pro", "sonar"},
	"perplexity-agent":     {"perplexity/sonar", "openai/gpt-5.5", "openai/gpt-5.4", "openai/gpt-5.4-mini", "anthropic/claude-sonnet-4-6", "anthropic/claude-opus-4-8", "google/gemini-3.1-pro-preview", "xai/grok-4.20-reasoning", "perplexity/glm-5.2", "perplexity/kimi-k2.7-code", "nvidia/nemotron-3-super-120b-a12b"},
	"perplexity-web":       {"pplx-auto", "pplx-sonar", "pplx-gpt", "pplx-gemini", "pplx-sonnet", "pplx-opus", "pplx-nemotron"},
	"poolside":             {"poolside/laguna-s-2.1", "poolside/laguna-xs-2.1"},
	"pplx":                 {"sonar-pro", "sonar"},
	"ps":                   {"poolside/laguna-s-2.1", "poolside/laguna-xs-2.1"},
	"pw":                   {"pplx-auto", "pplx-sonar", "pplx-gpt", "pplx-gemini", "pplx-sonnet", "pplx-opus", "pplx-nemotron"},
	"qd":                   {"ultimate", "auto", "performance", "efficient", "lite", "qmodel_38max", "qmodel_latest", "qmodel", "qfmodel", "kmodel_latest", "kmodel", "gmodel", "gfmodel", "dmodel", "dfmodel", "mmodel"},
	"qdcn":                 {"ultimate", "auto", "performance", "efficient", "lite", "qmodel_38max", "qmodel_latest", "qmodel", "qfmodel", "kmodel_latest", "kmodel", "gmodel", "gfmodel", "dmodel", "dfmodel", "mmodel"},
	"qianfan":              {"deepseek-v4-pro", "deepseek-v4-flash", "glm-5.2", "glm-5.1", "kimi-k2.6", "qwen3.5-397b-a17b", "qwen3.5-27b"},
	"qoder":                {"ultimate", "auto", "performance", "efficient", "lite", "qmodel_38max", "qmodel_latest", "qmodel", "qfmodel", "kmodel_latest", "kmodel", "gmodel", "gfmodel", "dmodel", "dfmodel", "mmodel"},
	"qoder-cn":             {"ultimate", "auto", "performance", "efficient", "lite", "qmodel_38max", "qmodel_latest", "qmodel", "qfmodel", "kmodel_latest", "kmodel", "gmodel", "gfmodel", "dmodel", "dfmodel", "mmodel"},
	"recraft":              {"recraftv3", "recraftv2"},
	"requesty":             {"nvidia/nemotron-3-ultra-550b-a55b", "nvidia/nemotron-3-super-120b-a12b", "nvidia/nemotron-3.5-lightning-30b-a3b", "nvidia/nemotron-3-nano-30b-a3b", "nvidia/muse-glimmer-30b", "google/gemma-4-31b-it", "mistral/leanstral-1-5", "novita/inclusionai/ling-3.0-tiny", "poolside/laguna-m.1"},
	"runway":               {"gen4_image", "gen4_image_turbo", "gen4_turbo", "gen3a_turbo"},
	"runwayml":             {"gen4_image", "gen4_image_turbo", "gen4_turbo", "gen3a_turbo"},
	"samba":                {"MiniMax-M2.7"},
	"sambanova":            {"MiniMax-M2.7"},
	"sdwebui":              {"stable-diffusion-v1-5", "sdxl-base-1.0"},
	"sea-lion":             {"aisingapore/Qwen-SEA-LION-v4.5-27B-IT", "aisingapore/Llama-SEA-LION-v3.5-70B-R", "aisingapore/Gemma-SEA-LION-v4-27B-IT", "aisingapore/SEA-Guard"},
	"selfhosted-embedding": {"embedding"},
	"selfhosted-stt":       {"whisper-1"},
	"selfhosted-tts":       {"kokoro"},
	"siliconflow":          {"deepseek-ai/DeepSeek-V4-Pro", "deepseek-ai/DeepSeek-V4-Flash", "deepseek-ai/DeepSeek-V3.2", "deepseek-ai/DeepSeek-V3.2-Exp", "deepseek-ai/DeepSeek-V3.1", "deepseek-ai/DeepSeek-V3.1-Terminus", "deepseek-ai/DeepSeek-R1", "Qwen/Qwen3.5-397B-A17B", "Qwen/Qwen3.5-122B-A10B", "zai-org/GLM-5.1", "zai-org/GLM-5", "moonshotai/Kimi-K2.6", "moonshotai/Kimi-K2.5", "openai/gpt-oss-120b", "MiniMaxAI/MiniMax-M2.5", "inclusionAI/Ling-flash-2.0"},
	"stability":            {"stable-image-ultra", "stable-image-core", "sd3.5-large", "sd3.5-large-turbo", "sd3.5-medium"},
	"stability-ai":         {"stable-image-ultra", "stable-image-core", "sd3.5-large", "sd3.5-large-turbo", "sd3.5-medium"},
	"tencent":              {"hunyuan-turbos-latest", "hunyuan-t1-latest"},
	"together":             {"meta-llama/Llama-3.3-70B-Instruct-Turbo", "deepseek-ai/DeepSeek-R1", "Qwen/Qwen3-235B-A22B", "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", "BAAI/bge-large-en-v1.5", "togethercomputer/m2-bert-80M-8k-retrieval"},
	"tokenrouter":          {"anthropic/claude-haiku-4.5", "anthropic/claude-sonnet-4.6", "anthropic/claude-opus-4.8", "anthropic/claude-opus-4.8-fast", "openai/gpt-5.4", "openai/gpt-5.4-mini", "openai/gpt-5.4-pro", "openai/gpt-5.5", "openai/gpt-5.6-sol", "google/gemini-3.5-flash", "google/gemini-3.6-flash", "deepseek/deepseek-v4-flash", "deepseek/deepseek-v4-pro", "qwen/qwen3-coder-next", "qwen/qwen3.7-max", "qwen/qwen3.8-max", "moonshotai/kimi-k2.7-code", "moonshotai/kimi-k3-free", "z-ai/glm-5.3-free", "z-ai/glm-5.2", "z-ai/glm-5-turbo", "x-ai/grok-4.5"},
	"venice":               {"venice-uncensored-1-2", "zai-org-glm-5", "qwen3-235b-a22b-instruct-2507", "qwen3-coder-480b-a35b-instruct-turbo", "qwen3-vl-235b-a22b", "deepseek-v4-pro", "llama-3.3-70b", "hermes-3-llama-3.1-405b", "mistral-small-3-2-24b-instruct", "text-embedding-3-large", "text-embedding-bge-m3", "text-embedding-qwen3-8b", "venice-sd35", "flux-2-pro", "gpt-image-2"},
	"vertex":               {"gemini-3.1-pro-preview", "gemini-3.1-flash-lite-preview", "gemini-3-flash-preview", "gemini-2.5-flash", "veo-3.1-generate-preview", "veo-3.1-fast-generate-preview", "veo-3.0-generate-001", "veo-2.0-generate-001"},
	"vertex-partner":       {"deepseek-ai/deepseek-v3.2-maas", "qwen/qwen3-next-80b-a3b-thinking-maas", "qwen/qwen3-next-80b-a3b-instruct-maas", "zai-org/glm-5-maas"},
	"volcengine-ark":       {"Doubao-Seed-2.0-Code", "Doubao-Seed-2.0-pro", "Doubao-Seed-2.0-lite", "Doubao-Seed-Code", "DeepSeek-V4-Flash", "DeepSeek-V4-Pro", "GLM-5.1", "MiniMax-M2.7", "Kimi-K2.6"},
	"voyage":               {"voyage-3-large", "voyage-3.5", "voyage-3.5-lite", "voyage-code-3", "voyage-finance-2", "voyage-law-2", "voyage-multilingual-2"},
	"voyage-ai":            {"voyage-3-large", "voyage-3.5", "voyage-3.5-lite", "voyage-code-3", "voyage-finance-2", "voyage-law-2", "voyage-multilingual-2"},
	"vx":                   {"gemini-3.1-pro-preview", "gemini-3.1-flash-lite-preview", "gemini-3-flash-preview", "gemini-2.5-flash", "veo-3.1-generate-preview", "veo-3.1-fast-generate-preview", "veo-3.0-generate-001", "veo-2.0-generate-001"},
	"vxp":                  {"deepseek-ai/deepseek-v3.2-maas", "qwen/qwen3-next-80b-a3b-thinking-maas", "qwen/qwen3-next-80b-a3b-instruct-maas", "zai-org/glm-5-maas"},
	"xai":                  {"grok-4.6", "grok-4.5", "grok-4", "grok-4-fast-reasoning", "grok-code-fast-1", "grok-3", "grok-2-image-1212", "grok-imagine-video"},
	"xiaomi-mimo":          {"mimo-x-pro-preview", "mimo-x-flash-preview", "mimo-v2.5-pro", "mimo-v2.5", "mimo-v2-omni", "mimo-v2-flash", "mimo-v2.5-tts"},
	"xiaomi-tokenplan":     {"mimo-v2.5-pro", "mimo-v2.5-pro-claude", "mimo-v2.5", "mimo-v2-pro", "mimo-v2-omni", "mimo-v2-tts", "mimo-v2.5-tts", "mimo-v2.5-tts-voiceclone", "mimo-v2.5-tts-voicedesign"},
	"xmtp":                 {"mimo-v2.5-pro", "mimo-v2.5-pro-claude", "mimo-v2.5", "mimo-v2-pro", "mimo-v2-omni", "mimo-v2-tts", "mimo-v2.5-tts", "mimo-v2.5-tts-voiceclone", "mimo-v2.5-tts-voicedesign"},
	"yolo-auto":            {"qwen3.8-flash", "yolo", "yolo-small"},
}

// ProviderModelKinds maps provider alias/ID → model id → service kind for the
// models that are not plain chat (image, tts, stt, embedding, video, systemone).
// Upstream carries the same `kind` field on those registry entries and /v1/models
// filters on it (modelKind() in src/app/api/v1/models/route.js); without it here
// media models would leak into the LLM list.
var ProviderModelKinds = map[string]map[string]string{
	"aai": {
		"best":            "stt",
		"nano":            "stt",
		"universal-2":     "stt",
		"universal-3-pro": "stt",
	},
	"ag": {
		"gemini-3.1-flash-image": "image",
	},
	"antigravity": {
		"gemini-3.1-flash-image": "image",
	},
	"assemblyai": {
		"best":            "stt",
		"nano":            "stt",
		"universal-2":     "stt",
		"universal-3-pro": "stt",
	},
	"bfl": {
		"flux-dev":           "image",
		"flux-kontext-max":   "image",
		"flux-kontext-pro":   "image",
		"flux-pro":           "image",
		"flux-pro-1.1":       "image",
		"flux-pro-1.1-ultra": "image",
	},
	"black-forest-labs": {
		"flux-dev":           "image",
		"flux-kontext-max":   "image",
		"flux-kontext-pro":   "image",
		"flux-pro":           "image",
		"flux-pro-1.1":       "image",
		"flux-pro-1.1-ultra": "image",
	},
	"cf": {
		"@cf/black-forest-labs/flux-1-schnell":          "image",
		"@cf/black-forest-labs/flux-2-dev":              "image",
		"@cf/black-forest-labs/flux-2-klein-4b":         "image",
		"@cf/black-forest-labs/flux-2-klein-9b":         "image",
		"@cf/bytedance/stable-diffusion-xl-lightning":   "image",
		"@cf/leonardo/lucid-origin":                     "image",
		"@cf/leonardo/phoenix-1.0":                      "image",
		"@cf/lykon/dreamshaper-8-lcm":                   "image",
		"@cf/runwayml/stable-diffusion-v1-5-img2img":    "image",
		"@cf/runwayml/stable-diffusion-v1-5-inpainting": "image",
		"@cf/stabilityai/stable-diffusion-xl-base-1.0":  "image",
	},
	"cloudflare-ai": {
		"@cf/black-forest-labs/flux-1-schnell":          "image",
		"@cf/black-forest-labs/flux-2-dev":              "image",
		"@cf/black-forest-labs/flux-2-klein-4b":         "image",
		"@cf/black-forest-labs/flux-2-klein-9b":         "image",
		"@cf/bytedance/stable-diffusion-xl-lightning":   "image",
		"@cf/leonardo/lucid-origin":                     "image",
		"@cf/leonardo/phoenix-1.0":                      "image",
		"@cf/lykon/dreamshaper-8-lcm":                   "image",
		"@cf/runwayml/stable-diffusion-v1-5-img2img":    "image",
		"@cf/runwayml/stable-diffusion-v1-5-inpainting": "image",
		"@cf/stabilityai/stable-diffusion-xl-base-1.0":  "image",
	},
	"codex": {
		"gpt-5.3-image":          "image",
		"gpt-5.4-image":          "image",
		"gpt-5.5-image":          "image",
		"gpt-5.6-luna-image":     "image",
		"gpt-5.6-sol-image":      "image",
		"gpt-5.6-terra-image":    "image",
		"gpt-image-1.5":          "image",
		"gpt-image-2":            "image",
		"gpt-image-2.5":          "image",
		"gpt-image-2.5-flare":    "image",
		"gpt-image-2.5-sunburst": "image",
	},
	"comfyui": {
		"flux-dev": "image",
		"sdxl":     "image",
	},
	"cx": {
		"gpt-5.3-image":          "image",
		"gpt-5.4-image":          "image",
		"gpt-5.5-image":          "image",
		"gpt-5.6-luna-image":     "image",
		"gpt-5.6-sol-image":      "image",
		"gpt-5.6-terra-image":    "image",
		"gpt-image-1.5":          "image",
		"gpt-image-2":            "image",
		"gpt-image-2.5":          "image",
		"gpt-image-2.5-flare":    "image",
		"gpt-image-2.5-sunburst": "image",
	},
	"deepgram": {
		"nova":          "stt",
		"nova-2":        "stt",
		"nova-3":        "stt",
		"whisper-large": "stt",
	},
	"dg": {
		"nova":          "stt",
		"nova-2":        "stt",
		"nova-3":        "stt",
		"whisper-large": "stt",
	},
	"fal": {
		"fal-ai/flux-pro/v1.1":              "image",
		"fal-ai/flux-pro/v1.1-ultra":        "image",
		"fal-ai/flux/dev":                   "image",
		"fal-ai/flux/schnell":               "image",
		"fal-ai/ideogram/v2":                "image",
		"fal-ai/recraft-v3":                 "image",
		"fal-ai/stable-diffusion-v35-large": "image",
	},
	"fal-ai": {
		"fal-ai/flux-pro/v1.1":              "image",
		"fal-ai/flux-pro/v1.1-ultra":        "image",
		"fal-ai/flux/dev":                   "image",
		"fal-ai/flux/schnell":               "image",
		"fal-ai/ideogram/v2":                "image",
		"fal-ai/recraft-v3":                 "image",
		"fal-ai/stable-diffusion-v35-large": "image",
	},
	"fireworks": {
		"nomic-ai/nomic-embed-text-v1.5": "embedding",
	},
	"gemini": {
		"embedding-001":                  "embedding",
		"gemini-2.0-flash":               "stt",
		"gemini-2.5-flash":               "stt",
		"gemini-2.5-flash-image":         "image",
		"gemini-2.5-flash-lite":          "stt",
		"gemini-2.5-flash-preview-tts":   "tts",
		"gemini-2.5-pro":                 "stt",
		"gemini-2.5-pro-preview-tts":     "tts",
		"gemini-3-pro-image-preview":     "image",
		"gemini-3.1-flash-image-preview": "image",
		"gemini-3.1-flash-tts-preview":   "tts",
		"gemini-embedding-001":           "embedding",
		"gemini-embedding-2-preview":     "embedding",
		"text-embedding-004":             "embedding",
		"text-embedding-005":             "embedding",
	},
	"gh": {
		"text-embedding-3-large": "embedding",
		"text-embedding-3-small": "embedding",
	},
	"github": {
		"text-embedding-3-large": "embedding",
		"text-embedding-3-small": "embedding",
	},
	"groq": {
		"distil-whisper-large-v3-en": "stt",
		"whisper-large-v3":           "stt",
		"whisper-large-v3-turbo":     "stt",
	},
	"hf": {
		"HiDream-ai/HiDream-I1-Fast":                    "image",
		"Qwen/Qwen-Image":                               "image",
		"Qwen/Qwen-Image-2512":                          "image",
		"Qwen/Qwen-Image-Edit":                          "image",
		"Qwen/Qwen-Image-Edit-2509":                     "image",
		"Qwen/Qwen-Image-Edit-2511":                     "image",
		"Tongyi-MAI/Z-Image-Turbo":                      "image",
		"black-forest-labs/FLUX.1-Kontext-dev":          "image",
		"black-forest-labs/FLUX.1-Krea-dev":             "image",
		"black-forest-labs/FLUX.1-dev":                  "image",
		"black-forest-labs/FLUX.1-schnell":              "image",
		"black-forest-labs/FLUX.2-dev":                  "image",
		"black-forest-labs/FLUX.2-klein-4B":             "image",
		"black-forest-labs/FLUX.2-klein-9B":             "image",
		"black-forest-labs/FLUX.2-klein-base-4B":        "image",
		"black-forest-labs/FLUX.2-klein-base-9B":        "image",
		"ideogram-ai/ideogram-4-fp8":                    "image",
		"krea/Krea-2-Turbo":                             "image",
		"openai/whisper-large-v3":                       "stt",
		"openai/whisper-large-v3-turbo":                 "stt",
		"playgroundai/playground-v2.5-1024px-aesthetic": "image",
		"stabilityai/stable-diffusion-3.5-large":        "image",
		"stabilityai/stable-diffusion-3.5-large-turbo":  "image",
		"stabilityai/stable-diffusion-xl-base-1.0":      "image",
		"tencent/HunyuanImage-3.0":                      "image",
	},
	"huggingface": {
		"HiDream-ai/HiDream-I1-Fast":                    "image",
		"Qwen/Qwen-Image":                               "image",
		"Qwen/Qwen-Image-2512":                          "image",
		"Qwen/Qwen-Image-Edit":                          "image",
		"Qwen/Qwen-Image-Edit-2509":                     "image",
		"Qwen/Qwen-Image-Edit-2511":                     "image",
		"Tongyi-MAI/Z-Image-Turbo":                      "image",
		"black-forest-labs/FLUX.1-Kontext-dev":          "image",
		"black-forest-labs/FLUX.1-Krea-dev":             "image",
		"black-forest-labs/FLUX.1-dev":                  "image",
		"black-forest-labs/FLUX.1-schnell":              "image",
		"black-forest-labs/FLUX.2-dev":                  "image",
		"black-forest-labs/FLUX.2-klein-4B":             "image",
		"black-forest-labs/FLUX.2-klein-9B":             "image",
		"black-forest-labs/FLUX.2-klein-base-4B":        "image",
		"black-forest-labs/FLUX.2-klein-base-9B":        "image",
		"ideogram-ai/ideogram-4-fp8":                    "image",
		"krea/Krea-2-Turbo":                             "image",
		"openai/whisper-large-v3":                       "stt",
		"openai/whisper-large-v3-turbo":                 "stt",
		"playgroundai/playground-v2.5-1024px-aesthetic": "image",
		"stabilityai/stable-diffusion-3.5-large":        "image",
		"stabilityai/stable-diffusion-3.5-large-turbo":  "image",
		"stabilityai/stable-diffusion-xl-base-1.0":      "image",
		"tencent/HunyuanImage-3.0":                      "image",
	},
	"mimo": {
		"mimo-v2.5-tts": "tts",
	},
	"minimax": {
		"minimax-image-01": "image",
		"speech-01-hd":     "tts",
		"speech-01-turbo":  "tts",
		"speech-02-hd":     "tts",
		"speech-02-turbo":  "tts",
		"speech-2.6-hd":    "tts",
		"speech-2.6-turbo": "tts",
		"speech-2.8-hd":    "tts",
		"speech-2.8-turbo": "tts",
	},
	"minimax-cn": {
		"speech-01-hd":     "tts",
		"speech-01-turbo":  "tts",
		"speech-02-hd":     "tts",
		"speech-02-turbo":  "tts",
		"speech-2.6-hd":    "tts",
		"speech-2.6-turbo": "tts",
		"speech-2.8-hd":    "tts",
		"speech-2.8-turbo": "tts",
	},
	"mistral": {
		"mistral-embed": "embedding",
	},
	"nanobanana": {
		"nanobanana-flash": "image",
		"nanobanana-pro":   "image",
	},
	"nb": {
		"nanobanana-flash": "image",
		"nanobanana-pro":   "image",
	},
	"nebius": {
		"Qwen/Qwen3-Embedding-8B": "embedding",
	},
	"nvidia": {
		"fastpitch":                    "tts",
		"nvidia/nv-embedqa-e5-v5":      "embedding",
		"nvidia/parakeet-ctc-1.1b-asr": "stt",
		"tacotron2":                    "tts",
	},
	"oc": {
		"jev-1.13-free": "systemone",
	},
	"ocz": {
		"jev-1.13":      "systemone",
		"jev-1.13-free": "systemone",
	},
	"openai": {
		"dall-e-2":               "image",
		"dall-e-3":               "image",
		"gpt-4o-mini-transcribe": "stt",
		"gpt-4o-mini-tts":        "tts",
		"gpt-4o-transcribe":      "stt",
		"gpt-image-1":            "image",
		"gpt-image-2.5":          "image",
		"gpt-image-2.5-flare":    "image",
		"gpt-image-2.5-sunburst": "image",
		"text-embedding-3-large": "embedding",
		"text-embedding-3-small": "embedding",
		"text-embedding-ada-002": "embedding",
		"tts-1":                  "tts",
		"tts-1-hd":               "tts",
		"whisper-1":              "stt",
	},
	"opencode": {
		"jev-1.13-free": "systemone",
	},
	"opencode-zen": {
		"jev-1.13":      "systemone",
		"jev-1.13-free": "systemone",
	},
	"openrouter": {
		"black-forest-labs/FLUX.1-schnell":          "image",
		"bytedance/seedance-2.0":                    "video",
		"google/imagen-3.0-generate-002":            "image",
		"google/veo-3.1":                            "video",
		"nvidia/llama-nemotron-embed-vl-1b-v2:free": "embedding",
		"openai/dall-e-3":                           "image",
		"openai/gpt-4o-mini-tts":                    "tts",
		"openai/gpt-image-1":                        "image",
		"openai/sora-2-pro":                         "video",
		"openai/text-embedding-3-large":             "embedding",
		"openai/text-embedding-3-small":             "embedding",
		"openai/text-embedding-ada-002":             "embedding",
		"openai/tts-1":                              "tts",
		"openai/tts-1-hd":                           "tts",
		"perplexity/pplx-embed-v1-0.6b":             "embedding",
		"perplexity/pplx-embed-v1-4b":               "embedding",
		"qwen/qwen3-embedding-8b":                   "embedding",
		"typesafe/jev-1.13":                         "systemone",
	},
	"recraft": {
		"recraftv2": "image",
		"recraftv3": "image",
	},
	"runway": {
		"gen3a_turbo":      "video",
		"gen4_image":       "image",
		"gen4_image_turbo": "image",
		"gen4_turbo":       "video",
	},
	"runwayml": {
		"gen3a_turbo":      "video",
		"gen4_image":       "image",
		"gen4_image_turbo": "image",
		"gen4_turbo":       "video",
	},
	"sdwebui": {
		"sdxl-base-1.0":         "image",
		"stable-diffusion-v1-5": "image",
	},
	"selfhosted-embedding": {
		"embedding": "embedding",
	},
	"selfhosted-stt": {
		"whisper-1": "stt",
	},
	"selfhosted-tts": {
		"kokoro": "tts",
	},
	"stability": {
		"sd3.5-large":        "image",
		"sd3.5-large-turbo":  "image",
		"sd3.5-medium":       "image",
		"stable-image-core":  "image",
		"stable-image-ultra": "image",
	},
	"stability-ai": {
		"sd3.5-large":        "image",
		"sd3.5-large-turbo":  "image",
		"sd3.5-medium":       "image",
		"stable-image-core":  "image",
		"stable-image-ultra": "image",
	},
	"together": {
		"BAAI/bge-large-en-v1.5":                    "embedding",
		"togethercomputer/m2-bert-80M-8k-retrieval": "embedding",
	},
	"venice": {
		"flux-2-pro":              "image",
		"gpt-image-2":             "image",
		"text-embedding-3-large":  "embedding",
		"text-embedding-bge-m3":   "embedding",
		"text-embedding-qwen3-8b": "embedding",
		"venice-sd35":             "image",
	},
	"vertex": {
		"veo-2.0-generate-001":          "video",
		"veo-3.0-generate-001":          "video",
		"veo-3.1-fast-generate-preview": "video",
		"veo-3.1-generate-preview":      "video",
	},
	"voyage": {
		"voyage-3-large":        "embedding",
		"voyage-3.5":            "embedding",
		"voyage-3.5-lite":       "embedding",
		"voyage-code-3":         "embedding",
		"voyage-finance-2":      "embedding",
		"voyage-law-2":          "embedding",
		"voyage-multilingual-2": "embedding",
	},
	"voyage-ai": {
		"voyage-3-large":        "embedding",
		"voyage-3.5":            "embedding",
		"voyage-3.5-lite":       "embedding",
		"voyage-code-3":         "embedding",
		"voyage-finance-2":      "embedding",
		"voyage-law-2":          "embedding",
		"voyage-multilingual-2": "embedding",
	},
	"vx": {
		"veo-2.0-generate-001":          "video",
		"veo-3.0-generate-001":          "video",
		"veo-3.1-fast-generate-preview": "video",
		"veo-3.1-generate-preview":      "video",
	},
	"xai": {
		"grok-2-image-1212":  "image",
		"grok-imagine-video": "video",
	},
	"xiaomi-mimo": {
		"mimo-v2.5-tts": "tts",
	},
}

// GetProviderModelKind returns the declared service kind for a model ("image",
// "tts", ...) or "" when the model is a plain LLM entry. Unknown providers or
// models return "" so callers can fall back to the id heuristic upstream also
// uses for dynamic catalogs.
func GetProviderModelKind(aliasOrID, modelID string) string {
	if byModel, ok := ProviderModelKinds[aliasOrID]; ok {
		if kind, ok := byModel[modelID]; ok {
			return kind
		}
	}
	if canon, ok := ProviderAliasMap[aliasOrID]; ok {
		if byModel, ok := ProviderModelKinds[canon]; ok {
			if kind, ok := byModel[modelID]; ok {
				return kind
			}
		}
	}
	return ""
}

// GetProviderModels returns the list of models for a provider or alias.
func GetProviderModels(aliasOrID string) []string {
	if models, ok := ProviderModels[aliasOrID]; ok {
		return models
	}
	if canon, ok := ProviderAliasMap[aliasOrID]; ok {
		if models, ok := ProviderModels[canon]; ok {
			return models
		}
	}
	return nil
}
