package providers

// RegistryAliases maps a provider id to the alias upstream publishes it under
// (open-sse/providers/registry: buildProviderEntry -> alias: r.uiAlias || r.alias).
// Providers absent here have no alias upstream, so their id is published
// verbatim (e.g. clinepass, nvidia, openrouter, openai).
//
// This is the display/routing prefix used by /v1/models; ProviderAliasMap below
// stays the alias -> canonical id table used when resolving incoming model ids.
var RegistryAliases = map[string]string{
	"antigravity":       "ag",
	"api-airforce":      "af",
	"assemblyai":        "aai",
	"aws-polly":         "polly",
	"baidu":             "qianfan",
	"bazaarlink":        "bzl",
	"black-forest-labs": "bfl",
	"blackbox":          "bb",
	"bluesminds":        "bm",
	"brave-search":      "brave",
	"byteplus":          "bpm",
	"chutes":            "ch",
	"claude":            "cc",
	"cline":             "cl",
	"cloudflare-ai":     "cf",
	"codebuddy-cn":      "cbcn",
	"codebuddy-intl":    "cbai",
	"codex":             "cx",
	"commandcode":       "cmc",
	"cursor":            "cu",
	"deepgram":          "dg",
	"deepseek":          "ds",
	"elevenlabs":        "el",
	"fal-ai":            "fal",
	"featherless":       "fl",
	"fish-audio":        "fish",
	"gemini-cli":        "gc",
	"github":            "gh",
	"google-pse":        "gpse",
	"grok-cli":          "gcli",
	"grok-web":          "gw",
	"huggingface":       "hf",
	"hyperbolic":        "hyp",
	"iflow":             "if",
	"jina-ai":           "jina",
	"kilo-gateway":      "kgw",
	"kilocode":          "kc",
	"kiro":              "kr",
	"mimo-free":         "mmf",
	"nanobanana":        "nb",
	"opencode":          "oc",
	"opencode-go":       "ocg",
	"opencode-zen":      "ocz",
	"perplexity":        "pplx",
	"perplexity-agent":  "pa",
	"perplexity-web":    "pw",
	"poolside":          "ps",
	"qoder":             "qd",
	"qoder-cn":          "qdcn",
	"runwayml":          "runway",
	"sambanova":         "samba",
	"stability-ai":      "stability",
	"tencent":           "hunyuan",
	"vercel-ai-gateway": "vercel",
	"vertex":            "vx",
	"vertex-partner":    "vxp",
	"volcengine-ark":    "ark",
	"voyage-ai":         "voyage",
	"xiaomi-mimo":       "mimo",
	"xiaomi-tokenplan":  "xmtp",
	"zed":               "zd",
}
